import random
from telegram import InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ContextTypes
from games.base_game import BaseGame

BAYRAQLАР = [
    {"olke":"Azərbaycan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png", "ipucu":"A","herf":10},
    {"olke":"Türkiyə", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/1280px-Flag_of_Turkey.svg.png", "ipucu":"T","herf":8},
    {"olke":"Rusiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/1280px-Flag_of_Russia.svg.png", "ipucu":"R","herf":6},
    {"olke":"Almaniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/1280px-Flag_of_Germany.svg.png", "ipucu":"A","herf":8},
    {"olke":"Fransa", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/1280px-Flag_of_France.svg.png", "ipucu":"F","herf":6},
    {"olke":"İtaliya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/1280px-Flag_of_Italy.svg.png", "ipucu":"İ","herf":7},
    {"olke":"İspaniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/1280px-Flag_of_Spain.svg.png", "ipucu":"İ","herf":8},
    {"olke":"Britaniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/1280px-Flag_of_the_United_Kingdom.svg.png","ipucu":"B","herf":9},
    {"olke":"ABŞ", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png","ipucu":"A","herf":3},
    {"olke":"Yaponiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png", "ipucu":"Y","herf":8},
    {"olke":"Çin", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/1280px-Flag_of_the_People%27s_Republic_of_China.svg.png","ipucu":"Ç","herf":3},
    {"olke":"Braziliya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/1280px-Flag_of_Brazil.svg.png", "ipucu":"B","herf":9},
    {"olke":"Hindistan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/1280px-Flag_of_India.svg.png", "ipucu":"H","herf":8},
    {"olke":"Kanada", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/1280px-Flag_of_Canada_%28Pantone%29.svg.png","ipucu":"K","herf":6},
    {"olke":"Avstraliya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/1280px-Flag_of_Australia_%28converted%29.svg.png","ipucu":"A","herf":9},
    {"olke":"Gürcüstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/1280px-Flag_of_Georgia.svg.png", "ipucu":"G","herf":8},
    {"olke":"Ukrayna", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/1280px-Flag_of_Ukraine.svg.png", "ipucu":"U","herf":7},
    {"olke":"Qazaxıstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/1280px-Flag_of_Kazakhstan.svg.png", "ipucu":"Q","herf":10},
    {"olke":"İsveç", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/1280px-Flag_of_Sweden.svg.png", "ipucu":"İ","herf":5},
    {"olke":"Norveç", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/1280px-Flag_of_Norway.svg.png", "ipucu":"N","herf":6},
    {"olke":"Polşa", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/1280px-Flag_of_Poland.svg.png", "ipucu":"P","herf":5},
    {"olke":"Niderland", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1280px-Flag_of_the_Netherlands.svg.png","ipucu":"N","herf":9},
    {"olke":"Portuqaliya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1280px-Flag_of_Portugal.svg.png", "ipucu":"P","herf":11},
    {"olke":"Meksika", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/1280px-Flag_of_Mexico.svg.png", "ipucu":"M","herf":7},
    {"olke":"Argentina", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1280px-Flag_of_Argentina.svg.png", "ipucu":"A","herf":9},
    {"olke":"Misir", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/1280px-Flag_of_Egypt.svg.png", "ipucu":"M","herf":5},
    {"olke":"Özbəkistan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/1280px-Flag_of_Uzbekistan.svg.png", "ipucu":"Ö","herf":10},
    {"olke":"Türkmənistan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/1280px-Flag_of_Turkmenistan.svg.png", "ipucu":"T","herf":12},
    {"olke":"Tacikistan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/1280px-Flag_of_Tajikistan.svg.png", "ipucu":"T","herf":10},
    {"olke":"Qırğızıstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/1280px-Flag_of_Kyrgyzstan.svg.png", "ipucu":"Q","herf":10},
    {"olke":"Macarıstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/1280px-Flag_of_Hungary.svg.png", "ipucu":"M","herf":9},
    {"olke":"Finlandiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/1280px-Flag_of_Finland.svg.png", "ipucu":"F","herf":9},
    {"olke":"Danimarka", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/1280px-Flag_of_Denmark.svg.png", "ipucu":"D","herf":8},
    {"olke":"İslandiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/1280px-Flag_of_Iceland.svg.png", "ipucu":"İ","herf":8},
    {"olke":"Bolqarıstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/1280px-Flag_of_Bulgaria.svg.png", "ipucu":"B","herf":10},
    {"olke":"Rumıniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/1280px-Flag_of_Romania.svg.png", "ipucu":"R","herf":8},
    {"olke":"Xorvatiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/1280px-Flag_of_Croatia.svg.png", "ipucu":"X","herf":9},
    {"olke":"Sloveniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/1280px-Flag_of_Slovenia.svg.png", "ipucu":"S","herf":9},
    {"olke":"Slovakiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/1280px-Flag_of_Slovakia.svg.png", "ipucu":"S","herf":9},
    {"olke":"Çexiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/1280px-Flag_of_the_Czech_Republic.svg.png", "ipucu":"Ç","herf":6},
    {"olke":"Estoniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/1280px-Flag_of_Estonia.svg.png", "ipucu":"E","herf":8},
    {"olke":"Latviya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/1280px-Flag_of_Latvia.svg.png", "ipucu":"L","herf":7},
    {"olke":"Litva", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/1280px-Flag_of_Lithuania.svg.png", "ipucu":"L","herf":5},
    {"olke":"Moldova", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/1280px-Flag_of_Moldova.svg.png", "ipucu":"M","herf":7},
    {"olke":"Albaniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/1280px-Flag_of_Albania.svg.png", "ipucu":"A","herf":8},
    {"olke":"Serbiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1280px-Flag_of_Serbia.svg.png", "ipucu":"S","herf":7},
    {"olke":"Bosniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/1280px-Flag_of_Bosnia_and_Herzegovina.svg.png", "ipucu":"B","herf":7},
    {"olke":"Malta", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/1280px-Flag_of_Malta.svg.png", "ipucu":"M","herf":5},
    
