import random
from telegram import InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ContextTypes
from games.base_game import BaseGame

BAYRAQLАР = [
    {"olke":"Azərbaycan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png", "ipucu":"A","herf":10},
    {"olke":"Türkiyə", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/1280px-Flag_of_Turkey.svg.png", "ipucu":"T","herf":8},
    {"olke":"Rusiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/1280px-Flag_of_Russia.svg.png", "ipucu":"R","herf":6},
    {"olke":"Almaniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/1280px-Flag_of_Germany.svg.png", "ipucu":"A","herf":8},
    {"olke":"Fransa", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/1280px-Flag_of_France.svg.png", "ipucu":"F","herf":6},
    {"olke":"İtaliya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/1280px-Flag_of_Italy.svg.png", "ipucu":"İ","herf":7},
    {"olke":"İspaniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/1280px-Flag_of_Spain.svg.png", "ipucu":"İ","herf":8},
    {"olke":"Britaniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/1280px-Flag_of_the_United_Kingdom.svg.png","ipucu":"B","herf":9},
    {"olke":"ABŞ", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png","ipucu":"A","herf":3},
    {"olke":"Yaponiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png", "ipucu":"Y","herf":8},
    {"olke":"Çin", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/1280px-Flag_of_the_People%27s_Republic_of_China.svg.png","ipucu":"Ç","herf":3},
    {"olke":"Braziliya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/1280px-Flag_of_Brazil.svg.png", "ipucu":"B","herf":9},
    {"olke":"Hindistan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/1280px-Flag_of_India.svg.png", "ipucu":"H","herf":8},
    {"olke":"Kanada", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/1280px-Flag_of_Canada_%28Pantone%29.svg.png","ipucu":"K","herf":6},
    {"olke":"Avstraliya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/1280px-Flag_of_Australia_%28converted%29.svg.png","ipucu":"A","herf":9},
    {"olke":"Gürcüstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/1280px-Flag_of_Georgia.svg.png", "ipucu":"G","herf":8},
    {"olke":"Ukrayna", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/1280px-Flag_of_Ukraine.svg.png", "ipucu":"U","herf":7},
    {"olke":"Qazaxıstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/1280px-Flag_of_Kazakhstan.svg.png", "ipucu":"Q","herf":10},
    {"olke":"İsveç", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/1280px-Flag_of_Sweden.svg.png", "ipucu":"İ","herf":5},
    {"olke":"Norveç", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/1280px-Flag_of_Norway.svg.png", "ipucu":"N","herf":6},
    {"olke":"Polşa", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/1280px-Flag_of_Poland.svg.png", "ipucu":"P","herf":5},
    {"olke":"Niderland", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1280px-Flag_of_the_Netherlands.svg.png","ipucu":"N","herf":9},
    {"olke":"Portuqaliya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1280px-Flag_of_Portugal.svg.png", "ipucu":"P","herf":11},
    {"olke":"Meksika", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/1280px-Flag_of_Mexico.svg.png", "ipucu":"M","herf":7},
    {"olke":"Argentina", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1280px-Flag_of_Argentina.svg.png", "ipucu":"A","herf":9},
    {"olke":"Misir", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/1280px-Flag_of_Egypt.svg.png", "ipucu":"M","herf":5},
    {"olke":"Özbəkistan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/1280px-Flag_of_Uzbekistan.svg.png", "ipucu":"Ö","herf":10},
    {"olke":"Türkmənistan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/1280px-Flag_of_Turkmenistan.svg.png", "ipucu":"T","herf":12},
    {"olke":"Tacikistan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/1280px-Flag_of_Tajikistan.svg.png", "ipucu":"T","herf":10},
    {"olke":"Qırğızıstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/1280px-Flag_of_Kyrgyzstan.svg.png", "ipucu":"Q","herf":10},
    {"olke":"Macarıstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/1280px-Flag_of_Hungary.svg.png", "ipucu":"M","herf":9},
    {"olke":"Finlandiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/1280px-Flag_of_Finland.svg.png", "ipucu":"F","herf":9},
    {"olke":"Danimarka", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/1280px-Flag_of_Denmark.svg.png", "ipucu":"D","herf":8},
    {"olke":"Norveç", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/1280px-Flag_of_Norway.svg.png", "ipucu":"N","herf":6},
    {"olke":"İslandiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/1280px-Flag_of_Iceland.svg.png", "ipucu":"İ","herf":8},
    {"olke":"Bolqarıstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/1280px-Flag_of_Bulgaria.svg.png", "ipucu":"B","herf":10},
    {"olke":"Rumıniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/1280px-Flag_of_Romania.svg.png", "ipucu":"R","herf":8},
    {"olke":"Xorvatiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/1280px-Flag_of_Croatia.svg.png", "ipucu":"X","herf":9},
    {"olke":"Sloveniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/1280px-Flag_of_Slovenia.svg.png", "ipucu":"S","herf":9},
    {"olke":"Slovakiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/1280px-Flag_of_Slovakia.svg.png", "ipucu":"S","herf":9},
    {"olke":"Çexiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/1280px-Flag_of_the_Czech_Republic.svg.png", "ipucu":"Ç","herf":6},
    {"olke":"Estoniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/1280px-Flag_of_Estonia.svg.png", "ipucu":"E","herf":8},
    {"olke":"Latviya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/1280px-Flag_of_Latvia.svg.png", "ipucu":"L","herf":7},
    {"olke":"Litva", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/1280px-Flag_of_Lithuania.svg.png", "ipucu":"L","herf":5},
    {"olke":"Moldova", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/1280px-Flag_of_Moldova.svg.png", "ipucu":"M","herf":7},
    {"olke":"Albaniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/1280px-Flag_of_Albania.svg.png", "ipucu":"A","herf":8},
    {"olke":"Serbiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1280px-Flag_of_Serbia.svg.png", "ipucu":"S","herf":7},
    {"olke":"Bosniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/1280px-Flag_of_Bosnia_and_Herzegovina.svg.png", "ipucu":"B","herf":7},
    {"olke":"Malta", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/1280px-Flag_of_Malta.svg.png", "ipucu":"M","herf":5},
    {"olke":"Kipr", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/1280px-Flag_of_Cyprus.svg.png", "ipucu":"K","herf":4},
    {"olke":"İndoneziya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/1280px-Flag_of_Indonesia.svg.png", "ipucu":"İ","herf":9},
    {"olke":"Malayziya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/1280px-Flag_of_Malaysia.svg.png", "ipucu":"M","herf":9},
    {"olke":"Filippin", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/1280px-Flag_of_the_Philippines.svg.png", "ipucu":"F","herf":8},
    {"olke":"Sinqapur", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/1280px-Flag_of_Singapore.svg.png", "ipucu":"S","herf":8},
    {"olke":"Monqolustan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/1280px-Flag_of_Mongolia.svg.png", "ipucu":"M","herf":10},
    {"olke":"İraq", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/1280px-Flag_of_Iraq.svg.png", "ipucu":"İ","herf":4},
    {"olke":"Suriya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/1280px-Flag_of_Syria.svg.png", "ipucu":"S","herf":5},
    {"olke":"Livan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/1280px-Flag_of_Lebanon.svg.png", "ipucu":"L","herf":5},
    {"olke":"İordaniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/1280px-Flag_of_Jordan.svg.png", "ipucu":"İ","herf":8},
    {"olke":"Küveyt", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/1280px-Flag_of_Kuwait.svg.png", "ipucu":"K","herf":6},
    {"olke":"Qətər", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/1280px-Flag_of_Qatar.svg.png", "ipucu":"Q","herf":5},
    {"olke":"Bəhreyn", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/1280px-Flag_of_Bahrain.svg.png", "ipucu":"B","herf":7},
    {"olke":"Oman", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/1280px-Flag_of_Oman.svg.png", "ipucu":"O","herf":4},
    {"olke":"Yəmən", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/1280px-Flag_of_Yemen.svg.png", "ipucu":"Y","herf":5},
    {"olke":"İsrail", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/1280px-Flag_of_Israel.svg.png", "ipucu":"İ","herf":6},
    {"olke":"Fələstin", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/1280px-Flag_of_Palestine.svg.png", "ipucu":"F","herf":8},
    {"olke":"Əfqanıstan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/1280px-Flag_of_the_Taliban.svg.png", "ipucu":"Ə","herf":9},
    {"olke":"Mərakeş", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/1280px-Flag_of_Morocco.svg.png", "ipucu":"M","herf":7},
    {"olke":"Əlcəzair", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/1280px-Flag_of_Algeria.svg.png", "ipucu":"Ə","herf":8},
    {"olke":"Tunis", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/1280px-Flag_of_Tunisia.svg.png", "ipucu":"T","herf":5},
    {"olke":"Liviya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/1280px-Flag_of_Libya.svg.png", "ipucu":"L","herf":5},
    {"olke":"Sudan", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/1280px-Flag_of_Sudan.svg.png", "ipucu":"S","herf":5},
    {"olke":"Efiopiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/1280px-Flag_of_Ethiopia.svg.png", "ipucu":"E","herf":8},
    {"olke":"Somali", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/1280px-Flag_of_Somalia.svg.png", "ipucu":"S","herf":6},
    {"olke":"Keniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/1280px-Flag_of_Kenya.svg.png", "ipucu":"K","herf":5},
    {"olke":"Uqanda", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/1280px-Flag_of_Uganda.svg.png", "ipucu":"U","herf":6},
    {"olke":"Tanzaniya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Tanzania.svg/1280px-Flag_of_Tanzania.svg.png", "ipucu":"T","herf":8},
    {"olke":"Nigeriya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/1280px-Flag_of_Nigeria.svg.png", "ipucu":"N","herf":7},
    {"olke":"Qana", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/1280px-Flag_of_Ghana.svg.png", "ipucu":"Q","herf":4},
    {"olke":"Kamerun", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/1280px-Flag_of_Cameroon.svg.png", "ipucu":"K","herf":7},
    {"olke":"Anqola", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/1280px-Flag_of_Angola.svg.png", "ipucu":"A","herf":6},
    {"olke":"Zimbabve", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/1280px-Flag_of_Zimbabwe.svg.png", "ipucu":"Z","herf":8},
    {"olke":"Botsvana", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/1280px-Flag_of_Botswana.svg.png", "ipucu":"B","herf":8},
    {"olke":"Namibiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/1280px-Flag_of_Namibia.svg.png", "ipucu":"N","herf":8},
    {"olke":"Seneqal", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/1280px-Flag_of_Senegal.svg.png", "ipucu":"S","herf":7},
    {"olke":"Mali", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/1280px-Flag_of_Mali.svg.png", "ipucu":"M","herf":4},
    {"olke":"Madaqaskar", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/1280px-Flag_of_Madagascar.svg.png", "ipucu":"M","herf":10},
    {"olke":"Kolumbiya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/1280px-Flag_of_Colombia.svg.png", "ipucu":"K","herf":9},
    {"olke":"Venesuela", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/1280px-Flag_of_Venezuela.svg.png", "ipucu":"V","herf":9},
    {"olke":"Ekvador", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/1280px-Flag_of_Ecuador.svg.png", "ipucu":"E","herf":7},
    {"olke":"Peru", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/1280px-Flag_of_Peru.svg.png", "ipucu":"P","herf":4},
    {"olke":"Boliviya", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/1280px-Flag_of_Bolivia.svg.png", "ipucu":"B","herf":8},
    {"olke":"Çili", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/85/Flag_of_Chile.svg/1280px-Flag_of_Chile.svg.png", "ipucu":"Ç","herf":4},
    {"olke":"Paraqvay", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/1280px-Flag_of_Paraguay.svg.png", "ipucu":"P","herf":8},
    {"olke":"Uruqvay", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/1280px-Flag_of_Uruguay.svg.png", "ipucu":"U","herf":7},
    {"olke":"Kuba", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/1280px-Flag_of_Cuba.svg.png", "ipucu":"K","herf":4},
    {"olke":"Yamayka", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/1280px-Flag_of_Jamaica.svg.png", "ipucu":"Y","herf":7},
    {"olke":"Haiti", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/1280px-Haiti.svg.png", "ipucu":"H","herf":5},
    {"olke":"Panama", "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/1280px-Flag_of_Panama.svg.png", "ipucu":"P","herf":6},
